# Generated by Django 4.2.7 on 2023-11-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commet',
            new_name='Comment',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_created_0e6ed4_idx',
            old_name='blog_commet_created_6ea9fe_idx',
        ),
    ]
